version: '2.0'
services:
  tasker:
    build: 
      context: .
      dockerfile: Dockerfile-tasker
    image: reg.kpron.org:5000/tasker
    environment:
      ADMIN_TELEGRAM_ID: 75390371
      BOT_TOKEN: 278117953:AAFEsB8zg4r-XB7vtbPTtHyXXBe6bmD3krM
      DB_HOST: tasker_db
      DB_NAME: tasker
      DB_PASS: tasker
      DB_USER: tasker
      LOG_LEVEL: DEBUG
      MODE: develop
      SUPER_PORT: 9002
      HTTP_HOST: mocks.lol
    links:
      - tasker_db
    depends_on: 
      - tasker_db
    restart: always
  tasker_high:
    build: 
      context: .
      dockerfile: Dockerfile-tasker_high
    image: reg.kpron.org:5000/tasker-high
    environment:
      BOT_TOKEN: 278117953:AAFEsB8zg4r-XB7vtbPTtHyXXBe6bmD3krM
      DB_HOST: tasker_db
      DB_NAME: tasker
      DB_PASS: tasker
      DB_USER: tasker
      LOG_LEVEL: DEBUG
    links:
      - tasker_db
    depends_on: 
      - tasker_db
    restart: always
  tasker_db:
    build:
      context: .
      dockerfile: Dockerfile-tasker_db
    image: reg.kpron.org:5000/tasker-db
